name: ci
on: push

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  lint:
    name: Lint all the stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Linter
        uses: docker://github/super-linter:v3
